CREATE DATABASE SPMEDICAL_GROUP

USE SPMEDICAL_GROUP

CREATE TABLE TIPO_USUARIOS(
	ID_TIPO_USUARIO INT PRIMARY KEY IDENTITY
	,TIPO_USUARIO VARCHAR(200) NOT NULL
);

CREATE TABLE USUARIOS(
	ID_USUARIO INT IDENTITY PRIMARY KEY
	,ID_TIPO_USUARIO INT FOREIGN KEY REFERENCES TIPO_USUARIOS(ID_TIPO_USUARIO)
	,EMAIL_USUARIO VARCHAR(200)NOT NULL UNIQUE
	,SENHA_USUARIO VARCHAR(200) NOT NULL DEFAULT(RAND()*10)
);

CREATE TABLE PACIENTES(
	ID_PACIENTE INT PRIMARY KEY IDENTITY
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO)
	,NOME_PACIENTE VARCHAR(200) NOT NULL
	,NASCIMENTO_PACIENTE DATE NOT NULL
	,RG_PACIENTE CHAR(11) NOT NULL
	,CPF_PACIENTE CHAR(11) NOT NULL
	,TELEFONE_PACIENTE CHAR(14) NOT NULL
	,ENDERECO_PACIENTE VARCHAR(200) NOT NULL
	,INFORMACOES_PACIENTE TEXT
);

CREATE TABLE MEDICOS(
	ID_MEDICO INT PRIMARY KEY IDENTITY
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID_USUARIO)
	,NOME_MEDICO VARCHAR(250) NOT NULL
	,CRM_MEDICO CHAR(7) NOT NULL
	,ID_ESPECIALIDADE INT FOREIGN KEY REFERENCES ESPECIALIDADES(ID_ESPECIALIDADE)
	,ID_CLINICA INT FOREIGN KEY REFERENCES CLINICA(ID_CLINICA)
);

CREATE TABLE CONSULTAS(
	ID_CONSULTA INT PRIMARY KEY IDENTITY
	,ID_PACIENTE INT FOREIGN KEY REFERENCES PACIENTES(ID_PACIENTE)
	,ID_MEDICO  INT FOREIGN KEY REFERENCES MEDICOS(ID_MEDICO)
	,DATA_HORARIO DATETIME NOT NULL
	,DESCRICAO_CONSULTA TEXT
	,SITUACAO_CONSULTA CHAR(200) NOT NULL
);

CREATE TABLE ESPECIALIDADES(
	ID_ESPECIALIDADE INT PRIMARY KEY IDENTITY
	,ESPECIALIDADE_MEDICO CHAR(200) NOT NULL
);

CREATE TABLE CLINICA(
	ID_CLINICA  INT IDENTITY PRIMARY KEY
	,NOME_CLINICA VARCHAR(200) NOT NULL
	,CNPJ_CLINICA VARCHAR(14) NOT NULL
	,RAZAO_SOCIAL CHAR(200) NOT NULL
	,ENDERECO_CLINICA CHAR(200) NOT NULL
);