--Criação de software (web e mobile) de clínica médica
--Atividade do curso técnico Desenvolvimento de Sistemas
--Senai Informática São Paulo - 2019
--Instrutores: Helena Strada e Fernando Henrique Guerra
--Aluno: Daniel Roncaglia Correia dos Santos

--DBL - LINGUAGEM DE MANIPULAÇÃO DE DADOS

--INSERÇÃO DE DADOS NAS TABELAS DO BANCO DE DADOS

USE SPMEDICAL_GROUP;

INSERT INTO USUARIOS 
VALUES (1, 'adm@med.com', 12345), (2, 'daniel@med.com', 12345), (3, 'mariana@med.com', 12345)

INSERT INTO CONSULTAS
VALUES (1, 1, '2019-01-20T15:00:00' , 'problema de visão', 'realizada')

INSERT INTO ESPECIALIDADES VALUES ('Acupuntura'), ('Anestesiologia'), ('Angiologia'), ('Cardiologia')

INSERT INTO CLINICA VALUES ('Clinica Possarle',	'86400902000130', 'SP Medical Group', 'Av. Barão Limeira	532	 São Paulo	 SP')

INSERT INTO MEDICOS VALUES (5, 'João da Silva', '12345', 2, 1)

INSERT INTO PACIENTES VALUES (6,'Ligia', '13/10/1983', '43522543-5', '94839859000', '11 3456-7654', 'Rua Estado de Israel 240', 'novato')

INSERT INTO TIPO_USUARIOS VALUES ('Administrador'), ('Médico'), ('Paciente')

INSERT INTO CONSULTAS VALUEs (1, 4, '2019-01-20T15:00:00', 'Paciente com problemas de visão', 'Realizada')
   
SELECT * FROM usuarios


--CHAMA DADOS PARA TABELA OS DADOS DO ARQUIVO TIPO USUARIO
BULK INSERT TIPO_USUARIOS
FROM 'C:\db\tipo.csv'
	WITH (
		FORMAT = 'csv',
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		CODEPAGE = 'ACP', 
		DATAFILETYPE = 'Char'
	);

SELECT * FROM TIPO_USUARIOS

--CHAMA DADOS PARA TABELA OS DADOS DO ARQUIVO ESPECIALIDADES
BULK INSERT ESPECIALIDADES
FROM 'C:\db\especialidades.csv'
	WITH (
		FORMAT = 'csv',
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		CODEPAGE = 'ACP', 
		DATAFILETYPE = 'Char'
	);

SELECT * FROM ESPECIALIDADES

--CHAMA DADOS PARA TABELA OS DADOS DO ARQUIVO CLINICA
BULK INSERT CLINICA
FROM 'C:\db\clinica.csv'
	WITH (
		FORMAT = 'csv',
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		CODEPAGE = 'ACP', 
		DATAFILETYPE = 'Char'
	);

SELECT * FROM CLINICA

--CHAMA DADOS PARA TABELA OS DADOS DO ARQUIVO USUARIOS
BULK INSERT USUARIOS
FROM 'C:\db\usuarios.csv'
	WITH (
		FORMAT = 'csv',
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		CODEPAGE = 'ACP', 
		DATAFILETYPE = 'Char'
	);

SELECT * FROM USUARIOS

--CHAMA DADOS PARA TABELA OS DADOS DO ARQUIVO PACIENTES
BULK INSERT PACIENTES
FROM 'C:\db\pacientes.csv'
	WITH (
		FORMAT = 'csv',
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		CODEPAGE = 'ACP', 
		DATAFILETYPE = 'Char'
	);

SELECT * FROM PACIENTES

--CHAMA DADOS PARA TABELA OS DADOS DO ARQUIVO MEDICOS
BULK INSERT MEDICOS
FROM 'C:\db\medicos.csv'
	WITH (
		FORMAT = 'csv',
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		CODEPAGE = 'ACP', 
		DATAFILETYPE = 'Char'
	);

SELECT * FROM MEDICOS

--CHAMA DADOS PARA TABELA OS DADOS DO ARQUIVO CONSULTAS
BULK INSERT CONSULTAS
FROM 'C:\db\consultas.csv'
	WITH (
		FORMAT = 'csv',
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '\n',
		CODEPAGE = 'ACP', 
		DATAFILETYPE = 'Char'
	);

SELECT * FROM CONSULTAS

--EXEMPLO DE INSERÇÃO, ALTERAÇÃO E ELIMINAÇÃO NA TABELA ESPECIALIDADE
INSERT INTO ESPECIALIDADES (ESPECIALIDADE_MEDICO) VALUES ('Veterinária');

UPDATE ESPECIALIDADES SET ESPECIALIDADE_MEDICO = 'Medicina Veterinária' WHERE ID_ESPECIALIDADE = 18;

DELETE FROM ESPECIALIDADES  WHERE ID_ESPECIALIDADE = 18;

SELECT * FROM USUARIOS;
select * from Tipo;

select * from consultas;